apiVersion: v1
kind: Service
metadata:
  name: notifi-service
  labels:
    app: notifi-service
spec:
  selector:
    app: notifi-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP